version: '3.8'
services:
  backend:
    build:
      context: ./server
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
