name: Build and Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    name: Build and Push Images for Backend and Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./Chmura/server
          file: ./Chmura/server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./Chmura/client
          file: ./Chmura/client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

  notify:
    name: Send Notification Email
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Get Commit Hash
        id: commit
        run: echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Build Completed"
          body: "The application has been successfully built, and the Docker images have been pushed to Docker Hub!  
          
          Repository: ${{ github.repository }}  
          Commit: ${{ github.sha }}"
          to: ${{ secrets.EMAIL }}
          from: ${{ secrets.EMAIL }}


  deploy:
    name: Deploy to Azure Web Apps
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend to Azure Web App
        id: deploy-backend-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_BACKEND_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          images: '${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest'

      - name: Deploy Frontend to Azure Web App
        id: deploy-frontend-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_FRONTEND_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
          images: '${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest'


  tests:
    name: Run Regression (Cypress) Tests
    needs: deploy
    runs-on: ubuntu-latest
    env:
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
    defaults:
      run:
        working-directory: ./Chmura/tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Wait for Frontend to be available
        run: npx wait-on ${{ env.FRONTEND_URL }}

      - name: Run Cypress tests
        run: npx cypress run --config baseUrl=${{ env.FRONTEND_URL }}



          

