name: Build and Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    name: Build and Push Images for Backend and Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./Chmura/server
          file: ./Chmura/server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./Chmura/client
          file: ./Chmura/client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

notify:
  name: Send Notification Email
  needs: build-and-push
  runs-on: ubuntu-latest
  steps:
    - name: Get Commit Hash
      id: commit
      run: echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Send Email Notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.example.com
        server_port: 587
        username: ${{ secrets.EMAIL }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Build Completed"
        body: "The application has been successfully built, and the Docker images have been pushed to Docker Hub!  
        
        Repository: ${{ github.repository }}  
        Commit: ${{ github.sha }}"
        to: ${{ secrets.EMAIL }}
        from: ${{ secrets.EMAIL }}

